### ISSUE TITLE
Multiple Structure Alignment Example doesn't work

### ISSUE THREAD

**Issue by pwrose** [biojava/biojava-tutorial#14]
* MultipleAlignment result = algorithm.align(atomArrays);

--> should this line read: MultipleAlignment result = multiple.align(atomArrays);

* System.out.println(MultipleAlignmentWriter.toFASTA(result));

--> after fixing the previous statement, the toFASTA method throws an exception.

* MultipleAlignmentDisplay.display(result);
--> display method does not exists

**Comment by lafita** [comment]
The classes that use Jmol were renamed to contain Jmol in its name, so this class is now called MultipleAlignmentJmolDisplay. I will update the example and also fix the type with algorithm/multiple.

I would recommend that you use the DemoMultipleMC classes inside the demo package in both the biojava-structure and the biojava-structure-gui modules, since they are up to day and should work without errors.

Thank you for reporting the errors in the example.

**Comment by lafita** [comment]
The `toFASTA` method was throwing a `NullPointer` because the `StructureIdentifiers` were not set in the example, so the headers of the FASTA alignment format were null.
